import React from 'react'

export const OrderView = () => {
  return (
    <div>
        OrderView
        <div className='orderview_body'>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Fugiat, omnis reiciendis. Nam ipsum possimus exercitationem maxime ducimus libero similique asperiores, blanditiis dolorum debitis provident deserunt, nihil laborum necessitatibus quibusdam, iste qui eos eaque. Dicta officia sit, quod illum pariatur voluptate similique nam odio ipsum facere cum perspiciatis nisi repellendus, minima adipisci, corporis nemo quia. Excepturi mollitia odio ea temporibus vel ipsum itaque tenetur voluptatem, at laborum repellendus quos repellat. Quisquam fugiat magnam rem laudantium aliquid fugit cum, commodi libero assumenda accusantium voluptatem, eligendi velit reiciendis inventore porro quis repellendus distinctio enim optio omnis minima quam unde accusamus! Dicta, adipisci odio.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores quos sapiente nulla veniam minima praesentium beatae maiores debitis, natus numquam obcaecati molestias excepturi molestiae omnis ullam. Repellat distinctio rem expedita, culpa odit perferendis voluptatum perspiciatis! Aperiam, tempore? Recusandae accusamus amet nisi consequatur dolorum quibusdam excepturi sit dolore nostrum iure! Maxime, distinctio voluptate! Expedita, nesciunt ipsum amet itaque id dicta facere, est architecto dolor rerum corporis necessitatibus. Quam quis quod perspiciatis repellat ipsum animi aut omnis, nihil molestias illum excepturi veniam saepe voluptatem quasi. Accusantium, dignissimos animi. Velit suscipit eius sunt cum quidem ea omnis corporis consectetur labore, assumenda enim dolores?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores quos sapiente nulla veniam minima praesentium beatae maiores debitis, natus numquam obcaecati molestias excepturi molestiae omnis ullam. Repellat distinctio rem expedita, culpa odit perferendis voluptatum perspiciatis! Aperiam, tempore? Recusandae accusamus amet nisi consequatur dolorum quibusdam excepturi sit dolore nostrum iure! Maxime, distinctio voluptate! Expedita, nesciunt ipsum amet itaque id dicta facere, est architecto dolor rerum corporis necessitatibus. Quam quis quod perspiciatis repellat ipsum animi aut omnis, nihil molestias illum excepturi veniam saepe voluptatem quasi. Accusantium, dignissimos animi. Velit suscipit eius sunt cum quidem ea omnis corporis consectetur labore, assumenda enim dolores?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores quos sapiente nulla veniam minima praesentium beatae maiores debitis, natus numquam obcaecati molestias excepturi molestiae omnis ullam. Repellat distinctio rem expedita, culpa odit perferendis voluptatum perspiciatis! Aperiam, tempore? Recusandae accusamus amet nisi consequatur dolorum quibusdam excepturi sit dolore nostrum iure! Maxime, distinctio voluptate! Expedita, nesciunt ipsum amet itaque id dicta facere, est architecto dolor rerum corporis necessitatibus. Quam quis quod perspiciatis repellat ipsum animi aut omnis, nihil molestias illum excepturi veniam saepe voluptatem quasi. Accusantium, dignissimos animi. Velit suscipit eius sunt cum quidem ea omnis corporis consectetur labore, assumenda enim dolores?
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores quos sapiente nulla veniam minima praesentium beatae maiores debitis, natus numquam obcaecati molestias excepturi molestiae omnis ullam. Repellat distinctio rem expedita, culpa odit perferendis voluptatum perspiciatis! Aperiam, tempore? Recusandae accusamus amet nisi consequatur dolorum quibusdam excepturi sit dolore nostrum iure! Maxime, distinctio voluptate! Expedita, nesciunt ipsum amet itaque id dicta facere, est architecto dolor rerum corporis necessitatibus. Quam quis quod perspiciatis repellat ipsum animi aut omnis, nihil molestias illum excepturi veniam saepe voluptatem quasi. Accusantium, dignissimos animi. Velit suscipit eius sunt cum quidem ea omnis corporis consectetur labore, assumenda enim dolores?
        </div>
    </div>
  )
}
